added random function
flowgrammers-org/flowgramming pull request #185
Opened 2023-05-30 12:05 UTC by vcolluto

Added a random function in run.js. The function returns a random number between 0 and the value of the parameter (excluding)

2023-07-01 21:41 UTC, rajkumaar23 requested changes
The fn works, just one small nit. 

Also, can you please make another PR [here](https://github.com/flowgrammers-org/flowgramming-manual/blob/main/src/math-functions.md) to update the help docs?

2023-07-01 21:41 UTC, rajkumaar23 commented on js/run.js
> + let strokeLow = {
```suggestion
let strokeLow = {
```

2023-07-01 21:41 UTC, rajkumaar23 commented on js/run.js
> +        return globalEval(variableName + '=' + 'Math.floor(Math.random() *' + variable + ')')
```suggestion
        return globalEval(variableName + '=' + 'Math.round(Math.random() *' + variable + ')')
```

I believe rounding is a better choice than floor-ing. 🤔

2023-07-02 10:42 UTC, vcolluto commented on js/run.js
> + let strokeLow = {
done!

2023-07-02 22:12 UTC, rajkumaar23 approved these changes
LGTM. Thanks!

2023-07-02 22:13 UTC, merged